### ISSUE TITLE
separate drive images

### ISSUE THREAD

**Issue by bamdadkhan** [unxmaal/aux_sdcard#3]
hello,

could you please provide the drive images separately? it would be great to be able to restore them to the sd card one by one without having to re-image the whole thing. especially when someone has more mac os drives after the a/ux part.

**Comment by pbernicchi** [comment]
Hi - this has been discussed but there are just too many variations in configurations - for example, I have A/UX (plus the MacPartition), a 7.1.1 partition (AppleShare Pro), 7.6 and an 8.1.  

May I recommend https://github.com/dburr/scsi2sd_to_hda and break out/burn each partition  individually. I have not personally tried it so YMMV. I'd expect to be some problems with the way A/UX creates slices within the partition but curious as to your success.
